### ISSUE TITLE
指令存在失效可能？

### ISSUE THREAD

**Issue by Ning-Off** [diyigemt/arona-reborn#1]
例如@Arona /攻略 小春，需要多次使用指令才会返回攻略图片。
![Uploading Screenshot_2023-11-20-17-52-49-64_9d26c6446fd7bb8e41d99b6262b17def.jpg…]()

**Comment by Ning-Off** [comment]
后续有放出部署包自行部署的可能吗？

**Comment by diyigemt** [comment]
有，失效目前一是后端是node写的，性能跟不上了，二是确实存在莫名其妙发不出图片的情况，正在修

**Comment by diyigemt** [comment]
> 后续有放出部署包自行部署的可能吗？

目前群聊接口处于内测状态，得看官方会不会放开限制

**Comment by diyigemt** [comment]
指令失效目前看起来是触碰到响应消息上限了，我怀疑是藤子那边的问题
