### ISSUE TITLE
关于希望加上(B站)动态推送

### ISSUE THREAD

**Issue by zzzoumou** [diyigemt/arona-reborn#2]
作者好！
第一次用issues不直达用法对不对
目前我挂的bot还能用 然后我在插件市场额外加了一个动态推送的插件 现在如果用的是qq官方的阿罗娜那这个推送功能还能用吗？作者有办法集成吗？
嗯嗯我就是问问没什么要求！🫰
![3b724099146a2ff0be77c04362df26f8](https://github.com/diyigemt/arona-reborn/assets/124541336/fe1888ab-94e8-4d87-9683-ad2bd8fcd8d3)

**Comment by diyigemt** [comment]
目前官方主动推送功能有非常大的限制，每个群**每个月**，只能推送**4条**消息，对的你没看错，就是4条/月
如果官方不放开限制，且野生框架还能继续用的情况下，不建议用这个(

**Comment by zzzoumou** [comment]
好的，收到！感谢大佬回答
