### ISSUE TITLE
图片体积发送问题

### ISSUE THREAD

**Issue by Torther** [diyigemt/arona-reborn#3]
自己用JavaScript搓了一个，有些图片发不出去，一看返回的内容：
```
[MESSAGE] Receive from  Torther(831336262654910889) : <@!18057699612238851909> /攻略 国际服未来视
{
  code: 40014,
  message: 'file too large',
  traceid: '96fc7bf53309f3bb6e72524f6d0b9b2b'
}
```
文件太大，发不出去，给我逗乐了，sb腾讯

**Comment by diyigemt** [comment]
好像频道限制4M，我图片压缩基准是5.5M的，这几天我会把新后端上了然后把图片压一遍，群接口用旧的图片，频道用新的

**Comment by Torther** [comment]
> 好像频道限制4M，我图片压缩基准是5.5M的，这几天我会把新后端上了然后把图片压一遍，群接口用旧的图片，频道用新的

开放平台上还没有群相关的内容，群bot是还在内测吗

**Comment by diyigemt** [comment]
是，群处于开发者大赛的内测中，12-20结束，可能结束后会开放
可是就现在的情况来看，这些bug可能结束后都没修好

**Comment by Torther** [comment]
今天写的时候，也发现攻略的模糊搜索很难实现选择，而且图片也没法保存到本地复用

**Comment by diyigemt** [comment]
模糊搜索只能等开放动态按钮的功能了
保存本地也只能等开放发送本地图片
总之就是等和等以及等，属于是完全没准备好就开放了

**Comment by Torther** [comment]
![image](https://github.com/diyigemt/arona-reborn/assets/29655416/9f283e5f-5743-48b3-8853-4d11620637ea)
哥，别发啦(😂)

**Comment by diyigemt** [comment]
哦忘了说了，新api支持频道的小图片发送了，自己去看文档
